### ISSUE TITLE
How to use with jsfiddle

### ISSUE THREAD

**Issue by jaichandra** [jscissr/react-polymer#13]
Can you please add some documentation (or provide pointers) on how to use this with react and if possible JSFiddle. It would help a lot for non-ReactJS developers, who want to test Polymer with React.

I used browserify on input.js and tried adding it on jsfiddle, but the data-binding is not working. 
http://jsfiddle.net/kleptomac/Lobmwfx6/1/

**Comment by jscissr** [comment]
I have never used react-polymer in jsfiddle, so I don't know any better than you how to make it work.

> how to use this with react

There is an example in the readme. Can you specify what is not clear?

**Comment by jaichandra** [comment]
In the demo folder, I ran `browserify build.js -o index-browserify.js` and tried running index-source.html, but its not working.

**Comment by jscissr** [comment]
Well, there is a `build.js` script in the demo folder that you need to run.

**Comment by jaichandra** [comment]
isn't this what you mean? `browserify build.js -o index-browserify.js`

**Comment by jscissr** [comment]
Nooo! `build.js` is a **build script**, not the source file! You should run `node build.js`, not browserify it (and maybe reset index-browserify.js to what it was before).

**Comment by jaichandra** [comment]
oooh.. sorry about that. Thanks
