### ISSUE TITLE
Impact of Polymer 2.0?

### ISSUE THREAD

**Issue by jaichandra** [jscissr/react-polymer#17]
@jscissr I would like to thank you first for creating this bridge between React and Polymer. Not sure how much time it took for you to figure out, which file and piece of code to monkey patch, but an awesome effort.

I see that in ShadyDOM* files, you mentioned that these are modified to use Polymer.dom API, which I completely understand. Now the question is, with Polymer 2.0 do we still need them? I believe, Polymer 2.0 is getting rid of Polymer.dom and using native API instead. Does it make it easier to integrate with ReactJS? Have you looked at it any further?

Thanks again.

**Comment by jscissr** [comment]
Yes, Polymer 2.0 does not have shady DOM anymore. But I also fixed several other problems with this project, and I don't know if they still work with 2.0. Because it is still 'unreleased preview', I have not looked at it yet.

**Comment by 0xR** [comment]
Polymer 2 is in RC now, maybe a good time to look at it again?

https://www.polymer-project.org/blog/2017-03-08-2-0-rc.html

**Comment by 0xR** [comment]
I discovered this project: https://github.com/webcomponents/react-integration Maybe this can replace this project? It seems to support custom elements v1 spec. So it should be able to work with polymer 2 as well.

**Comment by jscissr** [comment]
Polymer 2.0 is now supported in 4.0.0
