### ISSUE TITLE
Nesting Slot tag?

### ISSUE THREAD

**Issue by JoshuaKlassen** [jscissr/react-polymer#19]
Using regular Polymer if I have:
```
//some Polymer element A with template:
<div style="color:red">
    <slot></slot>
</div>
```

And then
```
//some Polymer element B with template:
<element-a>
    <slot></slot>
</element-a>
```

and finally I do something like:
```
<element-b>Hello World!</element-b>
```

the result is `Hello World!` goes all the way down to `element-a`, and is red.

However, I have had no luck with getting the same thing to work in `react-polymer`

```
//render returns:
<div>
    <element-b>
        <div>Hello from react!</div>
    </element-b>
</div>
```

It seems that the slot contents only go down 1 level, which I have found to not be the case otherwise

**Comment by jscissr** [comment]
Sorry, Polymer 2.0 is not yet supported, see #17.

**Comment by JoshuaKlassen** [comment]
I checked my Polymer version and it's v1.8.1
I also tried replacing `slot` with `content`, but I ran into the same issue
