### ISSUE TITLE
Can't get registerEvent working

### ISSUE THREAD

**Issue by 0xR** [jscissr/react-polymer#21]
I tried to copy the example in create-react-app and I can't get the `onResponse` handler working. This is my `index.js`: 

```js
import reactPolymer from 'react-polymer';
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

reactPolymer.registerEvent('response', 'onResponse');

ReactDOM.render(
  <iron-ajax
    auto
    url="https://httpbin.org/get"
    onResponse={console.log.bind(console)}
  />,
  document.getElementById('root')
);
```

I also added this import to `index.html`:
```html
<link rel="import" href="./bower_components/iron-ajax/iron-ajax.html">
```

Note that the ajax call is working. However I don't see anything logged in my console.

Maybe its good to provide a working demo of registerEvent. Currently the demo is only showing paper input elements.

**Comment by jscissr** [comment]
I guess using `iron-ajax` as an example, and not even testing it was not a good idea :thinking:. The reason it doesn't work is that the `onResponse` event does not bubble by default; it should work with

```
ReactDOM.render(
  <iron-ajax
    auto
    bubbles
    url="https://httpbin.org/get"
    onResponse={console.log.bind(console)}
  />,
  document.getElementById('root')
);
```
