### ISSUE TITLE
input.js fails in Webpack

### ISSUE THREAD

**Issue by dantman** [jscissr/react-polymer#4]
When using Webpack and importing `input.js` it fails with a syntax error due to the react syntax.

I tried changing loader config to explicitly run the `babel-loader` in `react-polymer/`, however it still fails. However it seems in that case it's because the .babelrc from the parent project is not used.

If you don't want to compile react-polymer before publishing, moving the presets config to a `.babelrc` and including it in the package should at least allow applying `babel-loader` to work.

**Comment by CarlosAmaral** [comment]
Same issue
