### ISSUE TITLE
Can not pass object via attribute

### ISSUE THREAD

**Issue by Qvatra** [jscissr/react-polymer#5]
I have tried the following:

```
reactPolymer.registerAttribute("entity");
reactPolymer.registerAttribute("config");

var myElement = React.createElement("polymer-element", { 
   entity: "polymer-entity-1",
   config: {
      string: "string",
      arr: [1, 2],
   },
});

var root = React.createElement("ul", { className: "container" }, myElement );
ReactDom.render(root, this.$.reactContainer);
```

as a result my 'polymer-element' receives id as a string and config object also as a string.
**typeof config** inside polymer element gives **"string"**.
Value of the string is "[object Object]"

how can I pass objects?

**UPDATE:**
I've removed

```
reactPolymer.registerAttribute("entity");
reactPolymer.registerAttribute("config");
```

and it still works. Why do we need to register attributes then?

**Comment by jscissr** [comment]
You can attach a `ref` function and set object properties there:

``` js
var myElement = React.createElement("polymer-element", { 
  entity: "polymer-entity-1",
  ref: function (ref) {
    if (!ref) return;
    ref.config = {
      string: "string",
      arr: [1, 2],
    };
  }
});
```

`registerAttribute` is only needed for custom attributes on **standard** elements (like `<div drawer>`).

Does this solve your problem?

**Comment by Qvatra** [comment]
Yes, thx
