### ISSUE TITLE
Uglify error when encountering `=>` function.

### ISSUE THREAD

**Issue by peterhry** [jscissr/react-polymer#8]
I get an error when I run `webpack -p`.

```
ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/react-polymer/index.js:66,0]
```

I notice line 66 is the only instance where an arrow function is used. When I change it to a regular function, the error goes away.

**Comment by jscissr** [comment]
You can use [babel-loader](http://webpack.github.io/docs/usage.html#transpiling-es2015-using-babel-loader), but make sure you don't exclude react-polymer:

```
exclude: s => /node_modules/.test(s) && !/react-polymer/.test(s),
```
